In [20]:
## This notebook investigates the association between individual diabetes medications administered during hospital stays and the likelihood of patient readmission.

## The goal is to identify specific medications that may be linked to higher or lower readmission rates. 
## Understanding these associations may help highlight treatment patterns correlated with readmission risk.

## Because this dataset is observational, the analysis focuses on statistical associations rather than causal relationships. 
## Logistic regression models will be used to estimate the relationship between medication use and readmission while controlling for patient characteristics 
## such as age, hospital utilization, and diagnostic complexity.

##Medication use in hospital settings is not randomly assigned. 
##Patients receiving certain treatments may differ systematically in disease severity or clinical presentation, a phenomenon known as confounding by indication. 
##Therefore, observed associations between medication use and readmission may reflect underlying patient characteristics rather than direct effects of the medications themselves.

import pandas as pd
import numpy as np

df = pd.read_csv(r"C:\Users\palla\OneDrive\Documents\Coding Projects\Hospital Diabetes Dataset\diabetic_data_utf8.csv")

df.shape

df.head()

df.columns

Index(['encounter_id', 'patient_nbr', 'race', 'gender', 'age', 'weight',
       'admission_type_id', 'discharge_disposition_id', 'admission_source_id',
       'time_in_hospital', 'payer_code', 'medical_specialty',
       'num_lab_procedures', 'num_procedures', 'num_medications',
       'number_outpatient', 'number_emergency', 'number_inpatient', 'diag_1',
       'diag_2', 'diag_3', 'number_diagnoses', 'max_glu_serum', 'A1Cresult',
       'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide',
       'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide',
       'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone',
       'tolazamide', 'examide', 'citoglipton', 'insulin',
       'glyburide-metformin', 'glipizide-metformin',
       'glimepiride-pioglitazone', 'metformin-rosiglitazone',
       'metformin-pioglitazone', 'change', 'diabetesMed', 'readmitted'],
      dtype='str')

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 50 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   encounter_id              101766 non-null  int64
 1   patient_nbr               101766 non-null  int64
 2   race                      101766 non-null  str
 3   gender                    101766 non-null  str
 4   age                       101766 non-null  str
 5   weight                    101766 non-null  str
 6   admission_type_id         101766 non-null  int64
 7   discharge_disposition_id  101766 non-null  int64
 8   admission_source_id       101766 non-null  int64
 9   time_in_hospital          101766 non-null  int64
 10  payer_code                101766 non-null  str
 11  medical_specialty         101766 non-null  str
 12  num_lab_procedures        101766 non-null  int64
 13  num_procedures            101766 non-null  int64
 14  num_medications           101766 non-null  int64
 15  number_outpatient         101766 non-null  int64
 16  number_emergency          101766 non-null  int64
 17  number_inpatient          101766 non-null  int64
 18  diag_1                    101766 non-null  str
 19  diag_2                    101766 non-null  str
 20  diag_3                    101766 non-null  str
 21  number_diagnoses          101766 non-null  int64
 22  max_glu_serum             5346 non-null    str
 23  A1Cresult                 17018 non-null   str
 24  metformin                 101766 non-null  str
 25  repaglinide               101766 non-null  str
 26  nateglinide               101766 non-null  str
 27  chlorpropamide            101766 non-null  str
 28  glimepiride               101766 non-null  str
 29  acetohexamide             101766 non-null  str
 30  glipizide                 101766 non-null  str
 31  glyburide                 101766 non-null  str
 32  tolbutamide               101766 non-null  str
 33  pioglitazone              101766 non-null  str
 34  rosiglitazone             101766 non-null  str
 35  acarbose                  101766 non-null  str
 36  miglitol                  101766 non-null  str
 37  troglitazone              101766 non-null  str
 38  tolazamide                101766 non-null  str
 39  examide                   101766 non-null  str
 40  citoglipton               101766 non-null  str
 41  insulin                   101766 non-null  str
 42  glyburide-metformin       101766 non-null  str
 43  glipizide-metformin       101766 non-null  str
 44  glimepiride-pioglitazone  101766 non-null  str
 45  metformin-rosiglitazone   101766 non-null  str
 46  metformin-pioglitazone    101766 non-null  str
 47  change                    101766 non-null  str
 48  diabetesMed               101766 non-null  str
 49  readmitted                101766 non-null  str
dtypes: int64(13), str(37)
memory usage: 38.8 MB

In [22]:
#Checking columns with missing values

df.isnull().sum().sort_values(ascending=False)

max_glu_serum               96420
A1Cresult                   84748
race                            0
gender                          0
age                             0
weight                          0
admission_type_id               0
discharge_disposition_id        0
admission_source_id             0
time_in_hospital                0
payer_code                      0
medical_specialty               0
num_lab_procedures              0
num_procedures                  0
num_medications                 0
number_outpatient               0
encounter_id                    0
patient_nbr                     0
number_inpatient                0
number_emergency                0
diag_1                          0
diag_2                          0
number_diagnoses                0
diag_3                          0
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      0
dtype: int64

In [23]:
# Proportion of patients readmitted within 30 days, after 30 days, and never readmitted

readmitted = df["readmitted"].value_counts(normalize=True)
print(readmitted)

readmitted
NO     0.539119
>30    0.349282
<30    0.111599
Name: proportion, dtype: float64

In [24]:
# Create a binary target variable for readmission within 30 days


medication_cols = [
    "metformin","repaglinide","nateglinide","chlorpropamide","glimepiride",
    "acetohexamide","glipizide","glyburide","tolbutamide","pioglitazone",
    "rosiglitazone","acarbose","miglitol","troglitazone","tolazamide",
    "examide","citoglipton","insulin","glyburide-metformin",
    "glipizide-metformin","glimepiride-pioglitazone",
    "metformin-rosiglitazone","metformin-pioglitazone"
]

med_usage_counts = (df[medication_cols] != "No").sum()

med_usage_counts.sort_values(ascending=False)

selected_meds = med_usage_counts[med_usage_counts >= 500].index.tolist()

print("Selected medications for analysis:")
print(selected_meds)

Selected medications for analysis:
['metformin', 'repaglinide', 'nateglinide', 'glimepiride', 'glipizide', 'glyburide', 'pioglitazone', 'rosiglitazone', 'insulin', 'glyburide-metformin']

In [25]:
#create a new column for each medication indicating whether it was used (1) or not (0)

used_columns= []

for med in selected_meds:
    new_col = med + "_used"
    df[new_col] = (df[med] != "No").astype(int)
    used_columns.append(new_col)

df[used_columns].head()

,metformin_used,repaglinide_used,nateglinide_used,glimepiride_used,glipizide_used,glyburide_used,pioglitazone_used,rosiglitazone_used,insulin_used,glyburide-metformin_used
0,0,0,0,0,0,0,0,0,0,0
1,0,0,0,0,0,0,0,0,1,0
2,0,0,0,0,1,0,0,0,0,0
3,0,0,0,0,0,0,0,0,1,0
4,0,0,0,0,1,0,0,0,1,0

In [28]:
df[used_cols].sum().sort_values(ascending=False)

NameError: name 'used_cols' is not defined

In [ ]:
# Check the proportion of patients readmitted within 30 days in the dataset

df["readmit_binary"] = (df["readmitted"] == "<30").astype(int)

df["readmit_binary"].mean()

np.float64(0.11159915885462728)

In [ ]:
#create a dictionary to hold readmission rates for each medication

readmit_rates = {}

for col in used_cols:
    
    rate = df.groupby(col)["readmit_binary"].mean()
    
    readmit_rates[col] = rate[1]   # rate among drug users

pd.Series(readmit_rates).sort_values(ascending=False)

repaglinide_used            0.133203
insulin_used                0.121380
glipizide_used              0.114457
nateglinide_used            0.113798
glyburide-metformin_used    0.110482
glyburide_used              0.106291
pioglitazone_used           0.105622
rosiglitazone_used          0.104478
glimepiride_used            0.102100
metformin_used              0.097008
dtype: float64

In [ ]:
severity_cols = [
    "age",
    "time_in_hospital",
    "num_medications",
    "number_inpatient",
    "number_emergency",
    "number_outpatient",
    "number_diagnoses"
]

df[severity_cols].describe().round(2)

,time_in_hospital,num_medications,number_inpatient,number_emergency,number_outpatient,number_diagnoses
count,101766.00,101766.00,101766.00,101766.00,101766.00,101766.00
mean,4.40,16.02,0.64,0.20,0.37,7.42
std,2.99,8.13,1.26,0.93,1.27,1.93
min,1.00,1.00,0.00,0.00,0.00,1.00
25%,2.00,10.00,0.00,0.00,0.00,6.00
50%,4.00,15.00,0.00,0.00,0.00,8.00
75%,6.00,20.00,1.00,0.00,0.00,9.00
max,14.00,81.00,21.00,76.00,42.00,16.00

In [ ]:
feature_cols = used_cols + severity_cols

X = df[feature_cols]
y = df["readmit_binary"]

X.shape



print(X.shape)   # 17 predictors
print(y.shape)      #one outcome per patient

(101766, 17)
(101766,)

In [19]:
from sklearn.model_selection import train_test_split

X_encoded = pd.get_dummies(X, drop_first=True)
X_encoded.shape

X_train, X_test, y_train, y_test = train_test_split(
    X_encoded,
    y,
    test_size=0.2,
    random_state=42,
    stratify=y
)

X_train.shape #confirming the training set has 80% of the data and 17 predictors

NameError: name 'X' is not defined

In [ ]:
model = LogisticRegression(max_iter=1000)
model.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [ ]:
coefficients = model.coef_[0]

coef_table = pd.DataFrame({
    "feature": X_train.columns,
    "coefficient": coefficients
})

print(coef_table)

NameError: name 'model' is not defined

In [ ]:
coef_table["odds_ratio"] = np.exp(coef_table["coefficient"])

coef_table.sort_values("odds_ratio", ascending=False)

NameError: name 'coef_table' is not defined

In [ ]:
coef_table[coef_table["feature"].str.contains("_used")]\
.sort_values("odds_ratio", ascending=False)

NameError: name 'coef_table' is not defined